[web]
web ansible_host=65.2.30.197 ansible_user=ubuntu ansible_ssh_private_key_file=~/ansible-key-priyank.pem

[db]
db ansible_host=10.1.2.44 ansible_user=ubuntu ansible_ssh_private_key_file=~/ansible-key-priyank.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/ansible-key-priyank.pem ubuntu@65.2.30.197 -W %h:%p"'
